### ISSUE TITLE
Beer scraper broken

### ISSUE THREAD

**Issue by shamrt** [alilja/ratebeer#19]
If I run the following line from `v2.3.0` of the package README…

    $ rb.beer("/beer/new-belgium-tour-de-fall/279122/")

…I get the following error:

    INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.ratebeer.com
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/Users/smartin/dev/workspaces/myliqbo/env/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 130, in beer
        return self.get_beer(url, True).__dict__
      File "/Users/smartin/dev/workspaces/myliqbo/env/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 126, in get_beer
        return models.Beer(url, fetch)
      File "/Users/smartin/dev/workspaces/myliqbo/env/lib/python2.7/site-packages/ratebeer/models.py", line 71, in __init__
        self._populate()
      File "/Users/smartin/dev/workspaces/myliqbo/env/lib/python2.7/site-packages/ratebeer/models.py", line 180, in _populate
        if overall_rating and overall_rating[1].text != 'n/a':
    IndexError: list index out of range

**Comment by OrganicIrradiation** [comment]
Looks to be an issue with the older version on PyPi. In the meantime, try installing with the following command and letting us know if it works:

    pip install git+git://github.com/alilja/ratebeer.git

@alilja, could you check it out?

**Comment by alilja** [comment]
Yeah — I'll get to it this weekend!

**Comment by shamrt** [comment]
Hi @alilja, have you had a chance to push the latest update to PyPI? Thanks!

**Comment by alilja** [comment]
[It is done.](https://pypi.python.org/pypi/ratebeer/2.3.1)
