### ISSUE TITLE
Cannot Fetch Beer

### ISSUE THREAD

**Issue by arfenarf** [alilja/ratebeer#25]
Hi, submitting a new issue, as I'm not sure poking the closed similar one does anyone any good.

I can search beers but I cannot retrieve beer data.

Here is typical output from test.py. TestBrewery all passed, as did TestMisc and TestSearch.  TestAlpha failed and of TestBeer, only the 404 scripts passed.  Can you help?

```
`Error
Traceback (most recent call last):
  File "/Users/kath/anaconda/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/kath/Documents/datacourse/udacity/04Exploratory_Analysis/project4/test.py", line 20, in test_beer
    results = RateBeer().beer('/beer/new-belgium-tour-de-fall/279122/')
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string or a number, not 'Tag'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): www.ratebeer.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /beer/new-belgium-tour-de-fall/279122/ HTTP/1.1" 200 37369
--------------------- >> end captured logging << ---------------------`
```

**Comment by OrganicIrradiation** [comment]
Hmm, I just tested my local branch and everything seemed to be fine:

```
(ratebeer) $ python test.py
~/.virtualenvs/ratebeer/lib/python3.5/site-packages/bs4/builder/_lxml.py:240: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  self.parser.feed(markup)
...................
----------------------------------------------------------------------
Ran 19 tests in 28.268s

OK
```

To confirm, I tested the version on github:

```
$ mkvirtualenv testratebeer
(testratebeer) $ pip install git+git://github.com/alilja/ratebeer.git
(testratebeer) $ wget https://raw.githubusercontent.com/alilja/ratebeer/master/test.py
(testratebeer) $ python test.py
~/.virtualenvs/testratebeer/lib/python3.5/site-packages/bs4/builder/_lxml.py:240: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  self.parser.feed(markup)
...................
----------------------------------------------------------------------
Ran 19 tests in 21.688s

OK
```

Perhaps try installing the pip version and see if the head version (on github) works for you by installing with:

```
pip install git+git://github.com/alilja/ratebeer.git
```

**Comment by arfenarf** [comment]
No joy - I even forced it to upgrade the other modules with `--upgrade` and it's throwing the same seven errors.  Let me double-check:  Python 2.7 should work?  I'm *this* close to dropping back and rebuilding python from the ground up but that might be overkill.

Thanks for your help...

    2379589875:~ kath$ python test.py
```
EE.EEEE.E..........
======================================================================
ERROR: test_fetch_by_letter (__main__.TestAlpha)
Make sure the results for a brewery list by index contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 161, in test_fetch_by_letter
    results = RateBeer().brewers_by_alpha("A")
AttributeError: 'RateBeer' object has no attribute 'brewers_by_alpha'

======================================================================
ERROR: test_beer (__main__.TestBeer)
Make sure the results for a beer contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 20, in test_beer
    results = RateBeer().beer('/beer/new-belgium-tour-de-fall/279122/')
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string or a number, not 'Tag'

======================================================================
ERROR: test_beer_closed_brewery (__main__.TestBeer)
Handling beers from closed brewers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in test_beer_closed_brewery
    results = RateBeer().beer('/beer/hantens-hildener-landbrau/140207/')
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 149, in _populate
    self.num_ratings = int(soup.find('span', itemprop="reviewCount").text)
AttributeError: 'NoneType' object has no attribute 'text'

======================================================================
ERROR: test_beer_closed_contract_brewery (__main__.TestBeer)
Handling beers from closed contract brewers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 45, in test_beer_closed_contract_brewery
    results = RateBeer().beer('/beer/crew-republic-x-11-wet-hop/298026/')
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string or a number, not 'Tag'

======================================================================
ERROR: test_beer_contract_brewed (__main__.TestBeer)
Handling contract brewed beers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in test_beer_contract_brewed
    results = RateBeer().beer('/beer/benediktiner-weissbier/157144/')
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string or a number, not 'Tag'

======================================================================
ERROR: test_beer_get_reviews (__main__.TestBeer)
Check to make multi-page review searches work properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 59, in test_beer_get_reviews
    self.assertIsNotNone(next(reviews))
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 212, in get_reviews
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string or a number, not 'Tag'

======================================================================
ERROR: test_beer_unicode (__main__.TestBeer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 68, in test_beer_unicode
    results = RateBeer().beer('/beer/steoji-oktoberbjor/292390/')
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 149, in _populate
    self.num_ratings = int(soup.find('span', itemprop="reviewCount").text)
AttributeError: 'NoneType' object has no attribute 'text'

----------------------------------------------------------------------
Ran 19 tests in 24.552s

FAILED (errors=7)
```

**Comment by OrganicIrradiation** [comment]
Happy to help!

I'm on a Mac using a Homebrew version of python, but it should not make a big difference.  I double-checked with Python 2.7 and the github version is fine:

```
$ mkvirtualenv testratebeer -p/usr/local/bin/python2
(testratebeer) $ pip install git+git://github.com/alilja/ratebeer.git
(testratebeer) $ https://raw.githubusercontent.com/alilja/ratebeer/master/test.py
(testratebeer) $ python test.py
...................
----------------------------------------------------------------------
Ran 19 tests in 25.718s

OK
```

I suspect it may be an issue with the pip version with the test.py that you are using. To confirm, I ran the following commands following the setup above:

```
(testratebeer) $ pip uninstall -y ratebeer
(testratebeer) $ pip install ratebeer
(testratebeer) $ python test.py
EE.EEEE.E..........
(OMITTED FOR BREVITY)
----------------------------------------------------------------------
Ran 19 tests in 22.286s

FAILED (errors=7)
```

Try the following:

```
$ pip uninstall ratebeer
$ pip install git+git://github.com/alilja/ratebeer.git
```

**Comment by arfenarf** [comment]
FIXED!  Thank you so very much.

\<does the happy-beer-data dance\>

**Comment by OrganicIrradiation** [comment]
Great to hear! Pinging @alilja because he might want to be aware that the PyPI version should be updated.
