### ISSUE TITLE
Broken Brewery

### ISSUE THREAD

**Issue by arfenarf** [alilja/ratebeer#26]
Thanks so much for your earlier help!  I've stumbled again.

If I understand things correctly, rb has changed their Brewery page so the brewery information is no longer wrapped in a div id='container' tag; and it's not in a table, either.  Calls to _populate(self) in models.py fail with a 'PageNotFound' error.

test_brewery, test_brewery_get_beers, and test_brewery_unicode fail, everything else (other than TestAlpha, which didn't work before on this machine) is OK.

I'm loath to tinker with this too much.  Would you mind confirming whether this error is more than just weirdness on my end?

```
Error
Traceback (most recent call last):
  File "/Users/kath/anaconda/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/kath/Documents/datacourse/udacity/04Exploratory_Analysis/project4/test.py", line 78, in test_brewery
    results = RateBeer().brewery("/brewers/deschutes-brewery/233/")
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 154, in brewery
    return self.get_brewery(url, True).__dict__
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/ratebeer.py", line 150, in get_brewery
    return models.Brewery(url, fetch)
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 293, in __init__
    self._populate()
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 340, in _populate
    raise rb_exceptions.PageNotFound(self.url)
PageNotFound: /brewers/deschutes-brewery/233/
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): www.ratebeer.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /brewers/deschutes-brewery/233/ HTTP/1.1" 200 24001
--------------------- >> end captured logging << ---------------------

```

**Comment by OrganicIrradiation** [comment]
Please excuse the (extreme) delay in response. These issues seem to have been fixed by PR #27, which was merged into the github repo. Could you please confirm? The github version is installable using pip with the following command:

     pip install git+git://github.com/alilja/ratebeer.git

**Comment by arfenarf** [comment]
Thanks for this - I fumbled around trying to make it work but decided I wasn't brave enough to ask yo to pull what I'd made.  Everything is working except: when I run test.py over the new code, I get all 'OK' except for test_brewery_get_beers, which dies with:
`
Error
Traceback (most recent call last):
  File "/Users/kath/anaconda/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/kath/Documents/datacourse/udacity/04Exploratory_Analysis/project4/test.py", line 93, in test_brewery_get_beers
    self.assertIsNotNone(next(beers))
  File "/Users/kath/anaconda/lib/python2.7/site-packages/ratebeer/models.py", line 386, in get_beers
    num_ratings = row.findAll('td')[7].text.strip()
`

This also happens when I run my own code and call beerport.

**Comment by OrganicIrradiation** [comment]
Fixed with a367a7664396619620e6e452b603758d14ee2995. Turns out they removed the "overall rating" field on the brewery's beers page, which is causing that issue.

**Comment by OrganicIrradiation** [comment]
I believe this problem has been fixed. Please let me know if it hasn't and we can reopen the issue.

**Comment by arfenarf** [comment]
Agreed, thanks.
