### ISSUE TITLE
Beginner's problem

### ISSUE THREAD

**Issue by CodersAreImaginative** [alilja/ratebeer#31]
Thanks to Andrew and everyone for making this excellent Ratebeer python module available in the public domain. This was just what I needed for a small hobby project of mine.

I realise you won't have time to help everybody who wants to use this library but I was wondering if the error I get when trying to access reviews is indicative of something having broken in the HTML interface of RateBeer relative to the assumptions being made in your python library of the same name or if (more likely) it's my inaptitude at getting it to work.

Specifically, I get an unexpected error message that seems to have to do with HTML parsing using BeautifulSoup.

**Comment by CodersAreImaginative** [comment]
FWIW this is what I get when I try to run test.py, which leads me to assume the error is on my side:

```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT4.
Type 'help' for help, type '?' for a list of *magic* commands.
Running script: "C:\Users\myself\Documents\Scripts\test.py"
Ec:\users\myself\miniconda3\lib\site-packages\bs4\builder\_lxml.py:250: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  self.parser.feed(markup)
E.EEEE.EEE.E.E.....
======================================================================
ERROR: test_fetch_by_letter (__main__.TestAlpha)
Make sure the results for a brewery list by index contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 167, in test_fetch_by_letter
    results = RateBeer().brewers_by_alpha("A")
AttributeError: 'RateBeer' object has no attribute 'brewers_by_alpha'

======================================================================
ERROR: test_beer (__main__.TestBeer)
Make sure the results for a beer contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 20, in test_beer
    results = RateBeer().beer('/beer/new-belgium-tour-de-fall/279122/')
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 72, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'

======================================================================
ERROR: test_beer_closed_brewery (__main__.TestBeer)
Handling beers from closed brewers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 41, in test_beer_closed_brewery
    results = RateBeer().beer('/beer/hantens-hildener-landbrau/140207/')
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 72, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 149, in _populate
    self.num_ratings = int(soup.find('span', itemprop="reviewCount").text)
AttributeError: 'NoneType' object has no attribute 'text'

======================================================================
ERROR: test_beer_closed_contract_brewery (__main__.TestBeer)
Handling beers from closed contract brewers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 46, in test_beer_closed_contract_brewery
    results = RateBeer().beer('/beer/crew-republic-x-11-wet-hop/298026/')
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 72, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'

======================================================================
ERROR: test_beer_contract_brewed (__main__.TestBeer)
Handling contract brewed beers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 52, in test_beer_contract_brewed
    results = RateBeer().beer('/beer/benediktiner-weissbier/157144/')
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 72, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'

======================================================================
ERROR: test_beer_get_reviews (__main__.TestBeer)
Check to make multi-page review searches work properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 60, in test_beer_get_reviews
    self.assertIsNotNone(next(reviews))
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 212, in get_reviews
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'

======================================================================
ERROR: test_beer_retired_beer (__main__.TestBeer)
Attributes for retired beers display properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 77, in test_beer_retired_beer
    results = RateBeer().beer('/beer/shorts-funkin-punkin/79468/')
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 72, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 134, in _populate
    self.overall_rating = int(soup.find('span', text='overall').next_sibling.next_sibling)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tag'

======================================================================
ERROR: test_beer_unicode (__main__.TestBeer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 69, in test_beer_unicode
    results = RateBeer().beer('/beer/steoji-oktoberbjor/292390/')
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 72, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 149, in _populate
    self.num_ratings = int(soup.find('span', itemprop="reviewCount").text)
AttributeError: 'NoneType' object has no attribute 'text'

======================================================================
ERROR: test_brewery (__main__.TestBrewery)
Make sure the results for a brewery contain the expected data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 338, in _populate
    s_contents = soup.find('div', id='container').find('table').find_all('tr')[0].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 84, in test_brewery
    results = RateBeer().brewery("/brewers/deschutes-brewery/233/")
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 153, in brewery
    return self.get_brewery(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 149, in get_brewery
    return models.Brewery(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 293, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 340, in _populate
    raise rb_exceptions.PageNotFound(self.url)
ratebeer.rb_exceptions.PageNotFound: /brewers/deschutes-brewery/233/

======================================================================
ERROR: test_brewery_get_beers (__main__.TestBrewery)
Check to make multi-page review searches work properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 338, in _populate
    s_contents = soup.find('div', id='container').find('table').find_all('tr')[0].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 99, in test_brewery_get_beers
    self.assertIsNotNone(next(beers))
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 365, in get_beers
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 340, in _populate
    raise rb_exceptions.PageNotFound(self.url)
ratebeer.rb_exceptions.PageNotFound: /brewers/deschutes-brewery/233/

======================================================================
ERROR: test_brewery_unicode (__main__.TestBrewery)
Check unicode brewery URLs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 338, in _populate
    s_contents = soup.find('div', id='container').find('table').find_all('tr')[0].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myself\Documents\Scripts\test.py", line 109, in test_brewery_unicode
    results = RateBeer().brewery("/brewers/brauhaus-18•80/12750/")
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 153, in brewery
    return self.get_brewery(url, True).__dict__
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\ratebeer.py", line 149, in get_brewery
    return models.Brewery(url, fetch)
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 293, in __init__
    self._populate()
  File "c:\users\myself\miniconda3\lib\site-packages\ratebeer-2.3.1-py3.5.egg\ratebeer\models.py", line 340, in _populate
    raise rb_exceptions.PageNotFound(self.url)
ratebeer.rb_exceptions.PageNotFound: /brewers/brauhaus-18•80/12750/

----------------------------------------------------------------------
Ran 20 tests in 21.642s

FAILED (errors=11)

The kernel process exited. (1)
```

**Comment by parryc** [comment]
Did you install using pip or directly from GitHub? If from pip, it may still be a few commits behind – try installing directly from GitHub with `pip install git+git://github.com/alilja/ratebeer.git`.

**Comment by CodersAreImaginative** [comment]
Thanks for your quick reply. I have since had the chance to try PyCharm running under OS/X where the workings of the pip command are a bit more transparent. I was thus able to successfully ask pip to install from GitHub rather than from the pypi repository and subsequently able to execute my test code without errors.

My problem has thus been reduced to finding out how to get the pip running in the shell of my Windows-based Python IDE to accept my request to install the module directly from GitHub rather than from PyPi. This presently fails with the following error message:

>>> pip install git+git://github.com/alilja/ratebeer.git
Collecting git+git://github.com/alilja/ratebeer.git
  Cloning git://github.com/alilja/ratebeer.git to c:\users\myself\miniconda3\lib\site-packages
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q git://github.com/alilja/ratebeer.git c:\users\myself\miniconda3\lib\site-packages
Cannot find command 'git'

I accept however that this has absolutely nothing to do with the ratebeer.py module and will thus go elsewhere for support in that regard. I would wish for however a more recent version of the module becoming available through PyPi.

**Comment by OrganicIrradiation** [comment]
Great, happy to hear. Also, a quick ping to @alilja to push the latest github version to PyPi.
