### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by andersenthomas** [alilja/ratebeer#56]
Is this project still active and working? I have installed ratebeer via pip but cannot get any of the examples to work.

`import ratebeer
rb = ratebeer.RateBeer()
rb.beer("/beer/new-belgium-tour-de-fall/279122/")`

`Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.8/site-packages/ratebeer/models.py", line 109, in _populate
    soup_rows = soup.find('div', id='container').find('table').find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thomas/.local/lib/python3.8/site-packages/ratebeer/ratebeer.py", line 143, in beer
    return self.get_beer(url, True).__dict__
  File "/home/thomas/.local/lib/python3.8/site-packages/ratebeer/ratebeer.py", line 139, in get_beer
    return models.Beer(url, fetch)
  File "/home/thomas/.local/lib/python3.8/site-packages/ratebeer/models.py", line 72, in __init__
    self._populate()
  File "/home/thomas/.local/lib/python3.8/site-packages/ratebeer/models.py", line 111, in _populate
    raise rb_exceptions.PageNotFound(self.url)
ratebeer.rb_exceptions.PageNotFound: /beer/new-belgium-tour-de-fall/279122/
>>> rb.brewery("/brewers/deschutes-brewery/233/")
Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.8/site-packages/ratebeer/models.py", line 338, in _populate
    s_contents = soup.find('div', id='container').find('table').find_all('tr')[0].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find'`

Any ideas?

**Comment by parryc** [comment]
Hi @andersenthomas, work on this project is effectively moribund. Please see https://github.com/OrganicIrradiation/ratebeer/issues/55 if you would like to see which features are missing. There are no plans at this time to update PyPi (since no one is really working on it and you can see from #55 that a lot of our features have broken).

That said, if you just need the ability to search for and get beer information, you can download directly from master and the basics should work. I have used the master checkout for basic lookups within the last 2 weeks without issue.

**Comment by andersenthomas** [comment]
Perfect. Thanks. I will try the master.
